#!/usr/bin/env bash

install_packages() {
  echo "Download package lists"
  sudo apt-get update -q -y 2>&1 >/dev/null

  echo "Update packages"
  sudo apt-get dist-upgrade -y 2>&1 >/dev/null

  echo "Install packages"
  sudo apt-get install -y anki python3-distutils vlc fonts-inconsolata \
       virtualbox mc deja-dup duplicity snapd deluge chromium-browser \
       2>&1 >/dev/null
  sudo fc-cache -fv
}

install_gnome_terminal_nord_theme() {
  wget https://raw.githubusercontent.com/arcticicestudio/nord-gnome-terminal/develop/src/nord.sh
  chmod +x nord.sh
  ./nord.sh
  rm nord.sh
}

install_resilio_sync() {
  echo "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free" | sudo tee /etc/apt/sources.list.d/resilio-sync.list
  curl -LO http://linux-packages.resilio.com/resilio-sync/key.asc && sudo apt-key add ./key.asc
  sudo apt-get update
  sudo apt-get install resilio-sync
}

do_all() {
  install_packages
  install_gnome_terminal_nord_theme
  install_resilio_sync
}

do_all
