#!/usr/bin/env bash

install_packages() {
  echo "Download package lists"
  sudo apt-get update -q -y 2>&1 >/dev/null

  echo "Update packages"
  sudo apt-get dist-upgrade -y 2>&1 >/dev/null

  echo "Install packages"
  sudo apt-get install -y vlc fonts-inconsolata virtualbox mc 2>&1 >/dev/null
  sudo fc-cache -fv
}

install_gnome_terminal_nord_theme() {
  wget https://raw.githubusercontent.com/arcticicestudio/nord-gnome-terminal/develop/src/nord.sh
  chmod +x nord.sh
  ./nord.sh
  rm nord.sh
}

do_all() {
  install_packages
  install_gnome_terminal_nord_theme
}

do_all
